merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name='band_list'),
    path('bands/<int:band_id>/', views.band_detail, name='band_detail'), # ajouter ce motif sous notre autre motif de groupes
    path('bands/add/', views.band_create, name='band-create'),
    path('bands/<int:id>/change/', views.band_update, name='band-update'),
    path('bands/<int:band_id>/delete/', views.band_delete, name='band-delete'),
    path('about-us/', views.about),
    path('contact-us/', views.contact, name='contact'),
    path( 'listing', views.listing_list, name='listing_list'),
    path('listing/<int:listing_id>/', views.listing_detail, name ='listing_detail' ),
    path('listing/add/', views.create_listing, name='listing-create'),
    path('listing/<int:id>/change/', views.listing_update, name='listing_update'),
    path('lisitng/<int:id>/delete/', views.listing_delete, name= 'listing_delete'),
    path('email-sent/', views.email_sent, name='email_sent'),  # Ajoutez ce chemin
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


# listings/models.py

class Band(models.Model):

    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(max_length=50)
    biography = models.fields.CharField(max_length=1000, default="Biographie par défaut")
    year_formed = models.fields.IntegerField(
    validators=[MinValueValidator(1900), MaxValueValidator(2024)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    def __str__(self):
        return f'{self.name}'

class Listing(models.Model):
    class Type(models.TextChoices):
        RECORDS = 'REC', 'Disques'
        CLOTHING = 'CLO', 'Vêtements'
        POSTERS = 'POS', 'Affiches'
        MISCELLANEOUS = 'MIS', 'Divers'

    title = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)
    sold = models.BooleanField(default=True)
    year = models.IntegerField(validators=[MinValueValidator(1900), MaxValueValidator(2024)])
    types = models.CharField(choices=Type.choices, max_length=30)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)
    like_new = models.fields.BooleanField(default=False)

    def __str__(self):
        return self.title

merchex/listings/forms.py
from django import forms
from listings.models import Band, Listing


class ContactUsForm(forms.Form):
   name = forms.CharField(required=False)
   email = forms.EmailField()
   message = forms.CharField(max_length=1000)



class BandForm(forms.ModelForm):
   class Meta:
     
     model = Band
     #fields = '__all__' # rajouter tous les champs
     exclude = ('active', 'official_homepage')  # ajoutez cette ligne


class ListingForm(forms.ModelForm): 
   class Meta :
      model = Listing
      fields = '__all__'
      

merchex/listings/views.py
# ~/projects/django-web-app/merchex/listings/views.py

from django.http import HttpResponse
from django.shortcuts import render
from listings.models import Band
from listings.models import Listing
from listings.forms import ContactUsForm
from django.core.mail import send_mail
from django.shortcuts import redirect  # ajoutez cet import
from listings.forms import BandForm, ContactUsForm, ListingForm

def band_list(request):  # renommer la fonction de vue
   bands = Band.objects.all()
   return render(request,
           'listings/band_list.html',  # pointe vers le nouveau nom de modèle
           {'bands': bands})



def about(request):
    return render(request, 'listings/about.html')

def contact(request):
    return render(request, 'listings/contact.html')

def listing_list(request):
    listings = Listing.objects.all()
    return render(request,'listings/listing_list.html', {'listings' : listings} )

def band_detail(request, band_id):
    band = Band.objects.get(id=band_id)
    return render(request, 'listings/band_detail.html', {'band': band})


def listing_detail(request, listing_id):
    listing = Listing.objects.get(id=listing_id)
    band = listing.band  # suppose que 'listing' a un champ 'band' qui est une relation vers un modèle Band
    return render(request, 'listings/listing_detail.html', {'listing': listing, 'band': band})


def contact(request):
    print('La méthode de requête est : ', request.method)
    print('Les données POST sont : ', request.POST)
    if request.method == 'POST':
    # créer une instance de notre formulaire et le remplir avec les données POST
        form = ContactUsForm(request.POST)
        if form.is_valid():
            send_mail(
            subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
            message=form.cleaned_data['message'],
            from_email=form.cleaned_data['email'],
            recipient_list=['admin@merchex.xyz'],
        )
        # si le formulaire n'est pas valide, nous laissons l'exécution continuer jusqu'au return
        # ci-dessous et afficher à nouveau le formulaire (avec des erreurs).
        return redirect('email-sent')  # ajoutez cette instruction de retour
    else:
    # ceci doit être une requête GET, donc créer un formulaire vide
        form = ContactUsForm()
    return render(request,
          'listings/contact.html',
          {'form': form})  # passe ce formulaire au gabarit

def email_sent(request):
    return render(request, 'listings/email_sent.html')

def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            # Créer une nouvelle instance « Band » et la sauvegarder dans la base de données
            band = form.save()
            # Rediriger vers la page de détail du groupe nouvellement créé
            return redirect('band_detail', band.id)   
    else:
        form = BandForm()

    return render(request, 'listings/band_create.html', {'form': form})

def create_listing(request): 
    if request.method == 'POST':
        form = ListingForm(request.POST)
        if form.is_valid():
            listing = form.save()
            return redirect('listing_detail', listing.id)
    else:
        form = ListingForm()

    return render(request, 'listings/create_listing.html', {'form': form})

def band_update(request, id):
    band = Band.objects.get(id=id)

    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            # mettre à jour le groupe existant dans la base de données
            form.save()
            # rediriger vers la page détaillée du groupe que nous venons de mettre à jour
            return redirect('band_detail', band.id)
    else:
        form = BandForm(instance=band)

    return render(request,
                'listings/band_update.html',
                {'form': form})

def listing_update(request, id): 
    listing = Listing.objects.get(id=id)
    if request.method == 'POST':
        form = ListingForm(request.POST, instance=listing)
        if form.is_valid():
            form.save()
            return redirect('listing_detail', listing.id)
    else: 
        form = ListingForm(instance=listing)
    return render(request, 'listings/listing_update.html', {'form' : form})



def band_delete(request, band_id):
    band = Band.objects.get(id=band_id)  # nécessaire pour GET et pour POST

    if request.method == 'POST':
        # supprimer le groupe de la base de données
        band.delete()
        # rediriger vers la liste des groupes
        return redirect('band_list')

    # pas besoin de « else » ici. Si c'est une demande GET, continuez simplement

    return render(request,
                    'listings/band_delete.html',
                    {'band': band})


def listing_delete(request, id):
    lisitng = Listing.objects.get(id=id)  # nécessaire pour GET et pour POST

    if request.method == 'POST':
        # supprimer le groupe de la base de données
        lisitng.delete()
        # rediriger vers la liste des groupes
        return redirect('listing_list')

    # pas besoin de « else » ici. Si c'est une demande GET, continuez simplement

    return render(request,
                    'listings/listing_delete.html',
                    {'listing': lisitng})

"""def hello(request):
    bands = Band.objects.all()
    listings = Listing.objects.all()
    return render (request, 'listings/hello.html',{'first_band': bands[0]})
"""

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{%block about %}
<h1>A propos de nous</h1>
{% endblock %}

merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}

{% block content %}

 <h1>Créer un nouveau groupe</h1>

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}

{% block content %}

 <h1>supprimer un  groupe</h1>


 <p>Etes-vous sûr de vouloir supprimer le groupe : {{ band.name }} ?</p>

 <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Supprimer">
    </form>

{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}
<h2>{{ band.name }}</h2>

<ul>
 <li>Genre : {{ band.genre }}</li>
 <li>Genre : {{ band.get_genre_display }}</li>
 <li>Année de formation : {{ band.year_formed }}</li>
 <li>Actif : {{ band.active }}</li>
 <li>{{ band.official_homepage }}</li>
</ul>

<h3>Articles associés :</h3>
<ul>
    {% for listing in band.listing_set.all %}
    <li>
        <a href="{% url 'listing_detail' listing.id %}">
            Voir les détails de : {{ listing.title }}
        </a>
    </li>
    {% empty %}
    <p>Aucun article associé à ce groupe.</p>
    {% endfor %}
</ul>

<p>{{ band.biography }}</p>

<a href="{% url 'band-update' band.id %}">Modifier ce groupe</a>
<a href="{% url 'band-delete' band.id %}">supprimer ce groupe</a>

<a href="{% url 'band_list' %}">Retour à tous les groupes</a>

{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Groupes</h1>

<ul>
 {% for band in bands %}
 <li><a href="{% url 'band_detail' band.id %}">{{ band.name }}</a></li> - <a href="{% url 'band-update' band.id %}">[modifier]</a>-<a href="{% url 'band-delete' band.id %}">[supprimer]</a>
 {% endfor %}
</ul>

<a href="{% url 'band-create' %}">Créer un nouveau groupe</a>

{% endblock %}

merchex/listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Mise à jour du groupe</h1>

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
    <title>Merchex</title>
</head>
<body>
    <nav>
        <a href="{% url 'band_list' %}">Groupes</a>
        <a href="{% url 'listing_list' %}"> listing</a>
        <a href="{% url 'contact'%}">contactez-nous</a>
      </nav>   

    {% block content %}{% endblock %}
    {% block contact %}{% endblock %}
    {% block about %}{% endblock %}
    {% block listing %}{% endblock %}
    {% block mail %}{% endblock %}
    {% block bandadd %}{% endblock %}
    
</body>
</html>

merchex/listings/templates/listings/contact.html
{% extends 'listings/base.html' %}

{%block contact %}
<h1>contactez-nous</h1>

<p>Nous sommes là pour vous aider.</p>

<form action="" method="post" novalidate> <!--pour empecher la validation du coté du serveur-->
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Envoyer">
</form>
{% endblock %}

merchex/listings/templates/listings/create_listing.html
{% extends 'listings/base.html' %}

{%block listing %}
<h1>Créer un nouveau produit</h1>

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/hello2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>hello django</title>
</head>
<body>
    <h1>Hello Django!</h1>
    <p>Mes groupes préférés sont :</p>
    <p>J'ai {{ bands|length }} groupes préférés.</p>
    <ul>
        {% for band in bands %}
        <li>{{ band.name }}</li>
        {% endfor %}
    </ul>

    <p>
        J'ai..
        {% if bands|length < 5 %}
            peu de
        {% elif bands|length < 10 %}
            quelques
        {% else %}
            beaucoup de
        {% endif %}
            groupes préférés.
    </p>

    <!--<li>{{first_band.name}}</li>-->
    <!--  <ul>
        <li>{{ bands.0.name }}</li>
        <li>{{ bands.1.name }}</li>
        <li>{{ bands.2.name }}</li>
    </ul>-->
    
    
</body>
</html>

merchex/listings/templates/listings/listing_delete.html
{% extends 'listings/base.html' %}

{% block listing %}

 <h1>supprimer cette objet</h1>


 <p>Etes-vous sûr de vouloir supprimer cette objet : {{ listing.title }} ?</p>

 <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Supprimer">
    </form>

{% endblock %}

merchex/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}

{% block listing %}
<h2>{{listing.title}}</h2>

<ul>
 <li>Genre : {{ listing.types }}</li>
 <li>Genre : {{ listing.get_types_display }}</li>
 <li>Année : {{ listing.year }}</li>
 <li>sold : {{ listing.sold }}</li>
 <li>like_new:{{ listing.like_new}}</li>
 <li></li><a href="{% url 'band_detail' band.id %}">{{ band.name }}</a></li>
</ul>

<p>{{ listing.description }}</p>


<!--<li><a href="{% url 'band_detail' band.id %}">{{ band.name }}</a></li>-->

<a href="{% url 'listing_update' listing.id %}">Modifier cette objet</a>
<a href="{% url 'listing_delete' listing.id %}">supprimer cette objet</a>
<a href="{% url 'listing_list' %}">Retour à tous les listing</a>

{% endblock %}

merchex/listings/templates/listings/listing_list.html
{% extends 'listings/base.html' %}

{%block listing %}
<p> mes affiches préférés</p>
<ul>
    {%for listing in listings%}
    <!--<li>{{listing.title}}</li>-->
    <li><a href="{% url 'listing_detail' listing.id %}">{{listing.title}}</a></li>- <a href="{% url 'listing_update' listing.id %}">[modifier]</a>-<a href="{% url 'listing_delete' listing.id %}">[supprimer]</a>
    {%endfor %}
</ul>

<a href="{% url 'listing-create' %}">Créer un nouveau objet</a>
{% endblock %}

merchex/listings/templates/listings/listing_update.html
{% extends 'listings/base.html' %}

{% block listing %}
<h1>Mise à jour de l'objet</h1>

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Envoyer">
</form>

{% endblock %}